### ISSUE TITLE
Only first 8 inputs showing in various actions, with (emulated)

### ISSUE THREAD

**Issue by PhillPower** [bitfocus/companion-module-analogway-awj#2] opened 2023-01-10 08:26 UTC
Companion v2.41 for Intel MacOS (also tested on ARM MacOS)

Aquilon C+ firmware v3.0.255

When selecting button actions such as Set Input Freeze or Select Layer Source, only the first 8 inputs are listed, all are shown with (emulated) after their name as in picture attached.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/49709309/211499224-a217507c-7512-4923-9fb4-ee7aa1762d9e.png">

**Comment by dnmeid** [comment] 2023-01-10 12:55
What version of the module is bundeled with your Companion 2.4.1?
What connections do you use in total? Especially are there more than one AWJ connections?

**Comment by PhillPower** [comment] 2023-01-10 15:53
v1.1.0

Currently running on a fresh version of Companion (Apple Silicon) with no other connections at all.

**Comment by dnmeid** [comment] 2023-01-10 22:46
So you write "various" actions. Is it in fact all actions or only some actions? If only some actions, the question is which actions. Maybe the actions which are only available at LivePremier and not at Midra.
My guess so far is that there is something wrong with the detection of the platform. LivePremier uses different commands than Alta/Midra. The module tries to check what platform is connected and then chooses the correct commands under the hood.
Can you check in the log/debug which device the module says it is connected to.
Have you ever been connected to a Midra or Alta or its simulators?

**Comment by PhillPower** [comment] 2023-01-13 21:13
> So you write "various" actions. Is it in fact all actions or only some actions?
Sorry, I didn't see your post until after the event, I won't have access to that particular Aquilon for a few weeks.

> Can you check in the log/debug which device the module says it is connected to.
Again sorry, but I left Companion running and the log is now full of `Connection attempt to device has timed out` because I forgot to disable the connection.

> Have you ever been connected to a Midra or Alta or its simulators?
Not with this module, no. I once used the old REST module to control a Pulse 4K, but that was back in March last year!

I ran up the LivePremier simulator when I got home and that seems to work fine. I'll have access to a brand new RS4 in a week, and then the original C+ the week after, so I can try again then.

**Comment by PhillPower** [comment] 2023-01-23 19:07
UPDATE: Trying with a brand new RS4 in the US, from the log: `instance(Aquilon): Connected to Aquilon RS4, S/N:GB0247`

The Actions affected:
- Set Input Keying
- Set Input Freeze
- Select Source in Multiviewer Widget
- Select Layer Source

And these Feedbacks:
- Source Tally
- Input Freeze

**Comment by dnmeid** [comment] 2023-02-20 00:15
To give you an unpdate: I've been rewriting the module for v3 now. Not ready for release yet, but working on my machine.
In my tests so far I could not reproduce the issue working on simulator with firmware 3.0.255 from Intel Macintosh.

**Comment by PhillPower** [comment] 2023-02-22 19:22
> To give you an unpdate: I've been rewriting the module for v3 now. Not ready for release yet, but working on my machine.
> In my tests so far I could not reproduce the issue working on simulator with firmware 3.0.255 from Intel Macintosh.

Excellent news, I look forward to trying it out.

Unfortunately I won't be anywhere near a real unit until early April, but I could have a play then if you have a version you want tested.

**Comment by PhillPower** [comment] 2023-04-09 12:13
UPDATE: Still having this issue with latest BFC Companion 3.0.0+5780 - my theory is currently that it's due to building the show on the simulator and then loading it onto a live machine.

I shall try to test this when I get a quiet moment in the theatre later.

**Comment by dnmeid** [comment] 2023-04-09 13:53
Keep me updated, I'd love to get this sorted before 13.4. but I don't have a real machine and noone else has reported this error.

**Comment by dnmeid** [comment] 2023-04-09 14:41
Can you please check the following:
when connected to your Aquilon, use your webbrowser to navigate to the site http://<aquilon-ip>/api/stores/device
it can take a while to load, maybe over 1 minute
then you should see a JSON-object named "device" and depending on your browser you can unfold sub-objects like you would navigate in a directory structure.
Open device/inputList/itemKeys and tell me what items you see there.
Open device/inputList/items/IN_1/status/pp and tell me if there are entries for "isAvailable" and "isEnabled" and what values they have.

**Comment by PhillPower** [comment] 2023-04-09 16:11
<img width="678" alt="image" src="https://user-images.githubusercontent.com/49709309/230783808-d130f702-a045-496c-bacd-916bc61f0a2a.png">

Won't connect, with or without internet.

**Comment by dnmeid** [comment] 2023-04-09 16:25
Ah, sorry it seems GitHub stripped out the ip adress. You have to use the ip of the aquilon between "http://" and "/api/stores/device"

**Comment by PhillPower** [comment] 2023-04-09 16:32
I guessed that might be the case, but all I get with Chrome or Safari is a large dump of text for a few moments before the page crashes out.
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/49709309/230784777-5aa8011c-8c0f-4353-b93b-e34a64c24106.png">

**Comment by dnmeid** [comment] 2023-04-09 16:37
what do you mean with "crashes out"? It looks like it should to me. It will download this huge object with a million lines and once it is finished after a long time it usually will render it in the directory like view.
I'm using firefox with no problems.

**Comment by dnmeid** [comment] 2023-04-09 16:56
this is Input "IN_1" from the simulator
<img width="517" alt="image" src="https://user-images.githubusercontent.com/8548888/230785864-f40bd5ea-ded3-4cde-b558-fdde4ca37525.png">

**Comment by PhillPower** [comment] 2023-04-09 16:56
> what do you mean with "crashes out"?

<img width="620" alt="image" src="https://user-images.githubusercontent.com/49709309/230785585-f82aeb42-5f81-4959-aff4-b8d79bea3d65.png">

> I'm using firefox with no problems.
Aha! That works.

> Open device/inputList/itemKeys and tell me what items you see there.
A list 0: "IN_1"
1: "IN_2" 
etc. down to 
31: "IN_32"

> Open device/inputList/items/IN_1/status/pp and tell me if there are entries for "isAvailable" and "isEnabled" and what values they have.
isAvailable: True
isEnabled: False

**Comment by dnmeid** [comment] 2023-04-09 17:02
Cool, we are getting closer. For an input to show up in the dropdown isAvailable and isEnabled have to be true. Can you check if you have at least one input which has true at both.

**Comment by PhillPower** [comment] 2023-04-09 17:11
I do not. IN_1 to IN_24 are true/false, IN_25 to IN_32 are false/false (It's a fully-loaded C+)

**Comment by dnmeid** [comment] 2023-04-09 17:18
So that is the reason why you don't see any inputs in dropdown choices. If no inputs are found I show 8 emulated inputs so people can work a little bit.
The question is why are all your inputs isEnabled = false.
In the simulator it is always true for isEnabled and isAvailable depends if there is a card in the slot.
Actually this property is a leftover. You could enable/disable inputs at the Ascender but can't do it at Aquilon.
I guess this is a bug of the Aquilon firmware.

**Comment by PhillPower** [comment] 2023-04-09 17:19
I wish we could still enable/disable inputs like we could on the Ascender!

**Comment by dnmeid** [comment] 2023-04-09 17:26
You can try to set it to true with a custom command, the path is: DeviceObject/$input/@items/IN_1/status/@props/isEnabled
At the simulator this is not doing anything, maybe you have to add an update with DeviceObject/$input/@items/IN_1/$plug/@items/1/settings/@props/xUpdate (value = boolean, true)

**Comment by dnmeid** [comment] 2023-04-09 17:35
If you don't need the features of the latest firmware, you can also try an older firmware for the Aquilon. But I still don't know if this is a problem of the firmware 3.0.255 or of this particular system, as you are the only one reporting it.

**Comment by dnmeid** [comment] 2023-04-14 23:50
Closing this as resolved now.
Although it doesn't seem to be a Companion problem, a workaround is provided in [58c4e6d](https://github.com/bitfocus/companion-module-analogway-awj/commit/58c4e6d170b9fcf51298154c8774132b1cffb457) (v2.2.0)

**Closed by dnmeid** 2023-04-14 23:50 UTC
